-- ================================================================
-- MIGRATION 016 — email_otps table for Resend-based OTP delivery
-- ================================================================
-- Replaces supabase.auth.signInWithOtp() for withdrawal security.
-- OTPs are stored here (service_role only), generated by the
-- send-otp Edge Function, and verified by verify-otp.
-- ================================================================

CREATE TABLE IF NOT EXISTS public.email_otps (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  email      TEXT        NOT NULL,
  otp        TEXT        NOT NULL,
  purpose    TEXT        NOT NULL DEFAULT 'withdrawal'
               CHECK (purpose IN ('withdrawal', 'general')),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '15 minutes',
  used_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup: is this OTP valid right now?
CREATE INDEX IF NOT EXISTS email_otps_lookup_idx
  ON public.email_otps (user_id, otp, purpose)
  WHERE used_at IS NULL;

-- Rate-limit check: how many OTPs sent to this user in the last hour?
CREATE INDEX IF NOT EXISTS email_otps_ratelimit_idx
  ON public.email_otps (user_id, purpose, created_at);

ALTER TABLE public.email_otps ENABLE ROW LEVEL SECURITY;

-- Edge Functions use SUPABASE_SERVICE_ROLE_KEY (bypasses RLS).
-- Regular users have no direct access.
CREATE POLICY "no_direct_user_access" ON public.email_otps
  AS RESTRICTIVE
  FOR ALL
  USING (false);
